### PR TITLE
feat: add test coverage comments to PRs

### PR DESCRIPTION
**Pull request by gaetjen**

### CODE REVIEW

**Comment by BrianEstrada** [comment]
I like this but how does it interact with repos that don't have the gradle plugin?

**Comment by gaetjen** [comment]
this might not work for all projects :|

ocpp e.g. has other paths.

**Comment by gaetjen** [comment]
this workflow is already only for gradle projects, no?

**Comment by gaetjen** [comment]
did some updates. if no test report is generated it will add a comment like this:
https://github.com/monta-app/service-ocpp/pull/1047#issuecomment-1771168177

I think that is ok.

multiple modules also work.

**Comment by gaetjen** [comment]
I'll take another look tomorrow.
having the comment would also nudge people to add the plugin to their projects though.

**Comment by gaetjen** [comment]
ok, so we could enable this:
> `skip-if-no-changes` - [optional {default: false}] If true, comment won't be added if there is no coverage information present for the files changed.

otoh, these are the projects currently using the workflow:
 - service-cpi-api
 - partner-api
 - service-ocpp
 - library-ocpp
 - service-grid
 - service-solar
 - library-micronaut

I'm slightly in favor of just leaving the comment there to nudge people, but ok with either outcome.

**Review by BrianEstrada — APPROVED** [review]
you'll need to communicate with the portal team to let them know about this, the rest is cpi so it's probably fine

**Pull request merged**
