### PR TITLE
fix: overwrite test artifacts

### PR DESCRIPTION
**Pull request by mronager**
Extension to https://github.com/monta-app/github-workflows/pull/88 but applied to all artifact uploads

### CODE REVIEW

**Review by EliasJorgensen — APPROVED** [review]

**Comment by BrianEstrada** [comment]
Any insights into why this suddenly became an issue?

**Comment by mronager** [comment]
@BrianEstrada https://github.com/monta-app/github-workflows/pull/57 was merged 2 days ago, and had a breaking change where it would throw a 409 conflict and fail, where previously it would likely just overwrite it

**Comment by BrianEstrada** [comment]
ok, I guess you only encounter the issue when the tests fail right? I guess that's probably why I didn't see it in my (rather limited) testing of the steps 😢 thanks for catching this and fixing it 🙏🏽

**Comment by mronager** [comment]
We deploy to both dev and staging for staging builds, so i think thats why it fails in this specific case :)

**Pull request merged**
