### PR TITLE
feat(v2): Adapt workflow to use AWS OIDC DEVOPS-154

### PR DESCRIPTION
**Pull request by HotThoughts**
Need to think about how to update the workflow without breaking existing workflows.
Tag, for example.

### CODE REVIEW

**Comment by BrianEstrada** [comment]
hmm how does this work without the secret?

**Comment by HotThoughts** [comment]
@BrianEstrada Correct we don't need static aws access and secret key.

I post a message in Slack a few days ago: https://monta-app01.slack.com/archives/C02BVKRUS6T/p1678192940755519
Also, this Jira ticket: https://montaapp.atlassian.net/browse/DEVOPS-154

**Comment by BrianEstrada** [comment]
@HotThoughts ok if you're ready to merge we can push this to v2

**Comment by HotThoughts** [comment]
I believe all services that use workflow V2 have an open PR. I am ready to merge this PR to branch `v2`. Once it is merged, I will merge all those open PRs. 

When you have time, could you ✅ this PR so I can merge it? @BrianEstrada

**Comment by BrianEstrada** [comment]
Looks good? maybe we should hop on a call and do this together?

**Review by BrianEstrada — APPROVED** [review]

**Pull request merged**
